import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "The Curator - Antigravity Sample",
  description: "Editorial e-commerce storefront generated by Antigravity.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-[var(--color-surface)] font-sans text-[var(--color-text)] antialiased`}>
        {children}
      </body>
    </html>
  );
}
